apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test46
  namespace: test
  labels:
    app: test46 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: test46 
  template:
    metadata:
      labels:
        app: test46
    spec: 
      containers: 
      - env:
        - name: TZ
          value: UTC
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: {{ registry_address }}:5000/test_images/spam_150_1_8001:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 8001 
          failureThreshold: 10 
          periodSeconds: 10 
          successThreshold: 1
          timeoutSeconds: 15
        name: t46-1
        readinessProbe:
          tcpSocket:
            port: 8001
          failureThreshold: 10
          initialDelaySeconds: 5 
          periodSeconds: 10 
          successThreshold: 1
          timeoutSeconds: 15
        resources:
          limits:
            cpu: 125m 
            ephemeral-storage: 2Gi
            memory: 300Mi
          requests:
            cpu: 100m
            ephemeral-storage: 1Gi
            memory: 200Mi 
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - MKNOD
            - all
          privileged: false
          readOnlyRootFilesystem: false 
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /logs
          name: log-shipper-storage-path
        - mountPath: /srv/ldap
          name: data
          subPath: data
        - mountPath: /etc/openldap/slapd.d
          name: data
          subPath: config-data
        - mountPath: /run/secrets/ldap-fed-passwd
          name: fedpasswd
          readOnly: true
        - mountPath: /run/secrets/tls-int-cert
          name: server-certificates
        - mountPath: /run/secrets/client-ca
          name: client-ca
        - mountPath: /run/secrets/ldap-syncuser-client-certificate
          name: ldap-syncuser-client-certificates
        - mountPath: /run/secrets/tls-int-ca-cert
          name: trusted-ca
          readOnly: true
        - mountPath: /run/secrets/internal-ca-cert
          name: internal-trusted-ca
          readOnly: true
      - env:
        - name: MESSAGE_LEN
          value: "240"
        - name: LOG_PERIOD_SEC
          value: "1/5"
        - name: POD_NAME
          valueFrom:
            fieldRef:
               fieldPath: metadata.name
        image: {{ registry_address }}:5000/test_images/logging:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - ls  
          failureThreshold: 3 
          initialDelaySeconds: 1 
          periodSeconds: 10 
          successThreshold: 1
          timeoutSeconds: 10
        name: sidecar-1 
        resources:
          limits:
            cpu: 125m 
            memory: 250Mi 
          requests:
            cpu: 75m
            memory: 150Mi 
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - MKNOD
            - all
          privileged: false
          readOnlyRootFilesystem: false 
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /logs
          name: log-shipper-storage-path
        - mountPath: /run/secrets/ca-certificates/
          name: server-ca-certificate
          readOnly: true
        - mountPath: /run/secrets/certificates/
          name: lt-client-cert
          readOnly: true
      initContainers:  
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: {{ registry_address }}:5000/ubi8/ubi
        imagePullPolicy: IfNotPresent
        name: t46-init
        resources:
          limits:
            cpu: 200m 
            ephemeral-storage: 2Gi
            memory: 2Gi
          requests:
            cpu: 160m 
            ephemeral-storage: 1Gi
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - MKNOD
            - all
          privileged: false
          readOnlyRootFilesystem: false 
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /logs
          name: log-shipper-storage-path
        - mountPath: /srv/ldap
          name: data
          subPath: data
        - mountPath: /etc/openldap/slapd.d
          name: data
          subPath: config-data
        - mountPath: /run/secrets/tls-int-cert
          name: server-certificates
        - mountPath: /run/secrets/client-ca
          name: client-ca
        - mountPath: /run/secrets/ldap-syncuser-client-certificate
          name: ldap-syncuser-client-certificates
        - mountPath: /run/secrets/tls-int-ca-cert
          name: trusted-ca
          readOnly: true
      volumes:
      - emptyDir:
          sizeLimit: 500Mi
        name: log-shipper-storage-path
      - name: server-ca-certificate
        secret:
          defaultMode: 420
          optional: true
          secretName: s186-2 
      - name: lt-client-cert
        secret:
          defaultMode: 420
          optional: true
          secretName: s178-2 
      - name: fedpasswd
        secret:
          defaultMode: 288
#          items:
#          - key: passwd
#            path: passwd
          secretName: s32-2 
      - name: server-certificates
        secret:
          defaultMode: 288
          secretName: s175-2 
      - name: client-ca
        secret:
          defaultMode: 288
          secretName: s31-1 
      - name: ldap-syncuser-client-certificates
        secret:
          defaultMode: 288
          secretName: s182-2 
      - name: trusted-ca
        secret:
          defaultMode: 288
          secretName: s186-2 
      - name: internal-trusted-ca
        secret:
          defaultMode: 288
          secretName: s33-1  
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-sc"
      resources:
        requests:
          storage: 10Gi

