apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: test42
  namespace: test
  labels:
    app: test42 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: test42 
  template:
    metadata:
      labels:
        app: test42
    spec: 
      containers: 
      - env:
        - name: TZ
          value: UTC
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: {{ registry_address }}:5000/ubi8/ubi
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 10;done"]
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - ls 
          failureThreshold: 3 
          initialDelaySeconds: 300 
          periodSeconds: 10 
          successThreshold: 1
          timeoutSeconds: 10
        name: t42-1
        readinessProbe:
          exec: 
            command:
            - ls
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 5 
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi 
          requests:
            cpu: 100m
            memory: 256Mi 
        securityContext:
          allowPrivilegeEscalation: false 
          capabilities:
            drop:
            - KILL
            - MKNOD
            - SETGID
            - SETUID
            - all
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /etc/consul/secrets
          name: gossip-key
          readOnly: true
      volumes:
      - name: gossip-key
        secret:
          defaultMode: 420
          secretName: s25-1 
  volumeClaimTemplates:
  - metadata:
      name: data 
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-sc"
      resources:
        requests:
          storage: 10Gi
