apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: test7
  namespace: test
  labels:
    app: test7 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: test7 
  template:
    metadata:
      labels:
        app: test7
    spec: 
      containers: 
      - env:
        - name: TZ
          value: UTC
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: {{ registry_address }}:5000/ubi8/ubi
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 10;done"]
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - ls 
          failureThreshold: 3
          initialDelaySeconds: 15 
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        name: t7-1
        readinessProbe:
          exec:
            command:
            - ls 
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        resources:
          limits:
            cpu: 350m 
            memory: 1Gi
          requests:
            cpu: 10m 
            memory: 400Mi 
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - MKNOD
              - all
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /run/zookeeper/secrets/servercert
          name: server-cert
        - mountPath: /run/zookeeper/secrets/siptlsca
          name: siptls-ca
        - mountPath: /run/zookeeper/secrets/clientca
          name: client-ca
        - mountPath: /run/zookeeper/secrets/clientcert
          name: client-cert
      - env:
        - name: MESSAGE_LEN
          value: "240"
        - name: LOG_PERIOD_SEC
          value: "1/5"
        - name: POD_NAME
          valueFrom:
            fieldRef:
               fieldPath: metadata.name
        image: {{ registry_address }}:5000/test_images/logging:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - ls
          failureThreshold: 3
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: sidecar-1 
        resources:
          limits:
            cpu: 125m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - MKNOD
            - all
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /logs
          name: log-shipper-storage-path
        - mountPath: /run/secrets/ca-certificates/
          name: server-ca-certificate
          readOnly: true
        - mountPath: /run/secrets/certificates/
          name: lt-client-cert
          readOnly: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: datadir-data-0
      - emptyDir:
          sizeLimit: 500Mi
        name: log-shipper-storage-path
      - name: server-ca-certificate
        secret:
          defaultMode: 420
          optional: true
          secretName: s186-2 
      - name: lt-client-cert
        secret:
          defaultMode: 420
          optional: true
          secretName: s28-2
      - name: server-cert
        secret:
          defaultMode: 420
          secretName: s29-2 
      - name: siptls-ca
        secret:
          defaultMode: 420
          secretName: s186-2 
      - name: client-ca
        secret:
          defaultMode: 420
          secretName: s5-1 
      - name: client-cert
        secret:
          defaultMode: 420
          secretName: s27-2 


