apiVersion: apps/v1
kind: Deployment
metadata:
  name: test22-deployment
  namespace: test
  labels:
    app: test22 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: test22 
  template:
    metadata:
      labels:
        app: test22
    spec: 
      containers: 
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: {{ registry_address }}:5000/ubi8/ubi
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 10;done"]
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - ls 
          failureThreshold: 3
          initialDelaySeconds: 1 
          periodSeconds: 10 
          successThreshold: 1
          timeoutSeconds: 10
        name: sidecar-1 
        resources:
          limits:
            cpu: 125m
            memory: 100Mi 
          requests:
            cpu: 50m
            memory: 50Mi 
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - KILL
              - MKNOD
              - SETGID
              - SETUID
              - all
            privileged: false
            readOnlyRootFilesystem: false 
            runAsNonRoot: true
        volumeMounts: 
        - mountPath: /logs
          name: log-shipper-storage-path
        - mountPath: /run/secrets/ca-certificates/
          name: server-ca-certificate
          readOnly: true
        - mountPath: /run/secrets/certificates/
          name: lt-client-cert
          readOnly: true
      - env:
        - name: TZ
          value: UTC
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: {{ registry_address }}:5000/test_images/spam_150_1_8001:latest 
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: 8001
          failureThreshold: 6 
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        name: t22-2
        readinessProbe:
          httpGet:
            path: /
            port: 8001 
          failureThreshold: 6
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        resources:
          limits:
            cpu: 200m
            ephemeral-storage: 2Gi
            memory: 600Mi
          requests:
            cpu: 100m
            ephemeral-storage: 2Gi
            memory: 30Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - KILL
            - MKNOD
            - SETGID
            - SETUID
            - all
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
        volumeMounts: 
        - mountPath: /app/tmp
          name: memory-storage
        - mountPath: /logs
          name: log-shipper-storage-path
        - mountPath: /app/etc/eric-fh-snmp-alarm-provider/secret
          name: secret-volume
          readOnly: true
        - mountPath: /app/etc/security/mtls/kafka/client
          name: kafka-certs-volume
          readOnly: true
        - mountPath: /app/etc/security/mtls/ah/client
          name: ah-certs-volume
          readOnly: true
        - mountPath: /app/etc/security/mtls/root
          name: serverca-volume
          readOnly: true
      volumes:
      - emptyDir:
        medium: Memory
        name: memory-storage
      - emptyDir:
        sizeLimit: 500Mi
        name: log-shipper-storage-path
      - name: server-ca-certificate
        secret:
          defaultMode: 420
          secretName: s186-2 
      - name: lt-client-cert
        secret:
          defaultMode: 420
          secretName: s84-2 
      - name: secret-volume
        secret:
          defaultMode: 420
          secretName: s24-1 
      - name: kafka-certs-volume
        secret:
          defaultMode: 420
          secretName: s189-2 
      - name: ah-certs-volume
        secret:
          defaultMode: 420
          secretName: s188-2 
      - name: serverca-volume
        secret:
          defaultMode: 420
          secretName: s186-2 
