apiVersion: apps/v1
kind: Deployment
metadata:
  name: test10-1-deployment
  namespace: test
  labels:
    app: test10-1 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: test10-1 
  template:
    metadata:
      labels:
        app: test10-1
    spec: 
      containers: 
      - env:
        - name: SERVICE_NAME
          value: t10-1 
        - name: CONTAINER_NAME
          value: t10-1 
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: {{ registry_address }}:5000/ubi8/ubi
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 10;done"]
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - ls 
          failureThreshold: 6 
          initialDelaySeconds: 10 
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        name: t10-1-1
        readinessProbe:
          exec:
            command:
            - ls 
          failureThreshold: 3 
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        resources:
          limits:
            cpu: 188m 
            memory: 2Gi 
            ephemeral-storage: 12Gi
          requests:
            cpu: 150m
            memory: 1Gi
            ephemeral-storage: 10Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - KILL
              - MKNOD
              - SETGID
              - SETUID
              - all
            privileged: false
            readOnlyRootFilesystem: false 
            runAsNonRoot: true
        volumeMounts:
        - mountPath: /tmp/certificates/ca/
          name: trusted-ca
        - mountPath: /tmp/certificates/bra/
          name: bra-client-certificates
        - mountPath: /var/data
          name: tmp-volume 
      - env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: TZ
          value: UTC
        image: {{ registry_address }}:5000/ubi8/ubi
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 10;done"]
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - ls
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 5 
          successThreshold: 1
          timeoutSeconds: 15
        readinessProbe:
          exec:
            command:
            - ls
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        name: t10-1-2
        resources:
          limits:
            cpu: 188m 
            memory: 512Mi
          requests:
            cpu: 150m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - KILL
            - MKNOD
            - SETGID
            - SETUID
            - all
          privileged: false
          readOnlyRootFilesystem: false 
          runAsNonRoot: true
        volumeMounts: 
        - mountPath: /var/data
          name: tmp-volume 
        - mountPath: /tmp/certificates/brm/
          name: brm-server-certificates
        - mountPath: /tmp/certificates/ca/
          name: trusted-ca
        - mountPath: /tmp/certificates/client/replica/
          name: replicauser-client-certificate
        - mountPath: /tmp/certificates/client/postgres/
          name: postgres-client-certificates
      - env:
        - name: MESSAGE_LEN
          value: "240"
        - name: LOG_PERIOD_SEC
          value: "1/5"
        - name: POD_NAME
          valueFrom:
            fieldRef:
               fieldPath: metadata.name
        image: {{ registry_address }}:5000/test_images/logging:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - ls
          failureThreshold: 3
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: sidecar-1 
        resources:
          limits:
            cpu: 125m
            memory: 250Mi
          requests:
            cpu: 50m
            memory: 150Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - MKNOD
            - all
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
      - emptyDir:
          medium: Memory
        name: tmp-volume
      - name: brm-server-certificates
        secret:
          defaultMode: 416
          secretName: s36-2 
      - name: trusted-ca
        secret:
          defaultMode: 416
          secretName: s186-2 
      - name: replicauser-client-certificate
        secret:
          defaultMode: 416
          secretName: s41-2 
      - name: bra-client-certificates
        secret:
          defaultMode: 416
          secretName: s35-2 
      - name: postgres-client-certificates
        secret:
          defaultMode: 416
          secretName: s40-2 
