apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "local-disks"
  namespace: "openshift-local-storage"
spec:
  storageClassDevices:
    - storageClassName: "local-sc"
      volumeMode: Filesystem
      fstype: xfs
      devicePaths:
        - /dev/new_vol_group/vol1
        - /dev/new_vol_group/vol2
        - /dev/new_vol_group/vol3
        - /dev/new_vol_group/vol4
        - /dev/new_vol_group/vol5
        - /dev/new_vol_group/vol6
        - /dev/new_vol_group/vol7
        - /dev/new_vol_group/vol8
        - /dev/new_vol_group/vol9
        - /dev/new_vol_group/vol10
        - /dev/new_vol_group/vol11
        - /dev/new_vol_group/vol12
        - /dev/new_vol_group/vol13
        - /dev/new_vol_group/vol14
        - /dev/new_vol_group/vol15
        - /dev/new_vol_group/vol16
        - /dev/new_vol_group/vol17
        - /dev/new_vol_group/vol18
        - /dev/new_vol_group/vol19
        - /dev/new_vol_group/vol20
        - /dev/new_vol_group/vol21
        - /dev/new_vol_group/vol22
        - /dev/new_vol_group/vol23
        - /dev/new_vol_group/vol24
        - /dev/new_vol_group/vol25
        - /dev/new_vol_group/vol26

