namespace: edu-namespace-0
debug_mode: false
setup_edu_ansible_verification: true
# spammer_per_mem_default: 50
# spammer_num_threads_default: 4
# spammer_per_cpu_default: 2

## Networking
networking:
  f1:
    vlan: 101
    ips: ["10.10.101.10/24"]
    gateway: "10.10.101.1"
  f1c:
    vlan: 102
    ips: ["10.10.102.10/24"]
    gateway: "10.10.102.1"
  fhm:
    vlan: 103
    ips: ["10.10.103.10/24"]
    gateway: "10.10.103.1"
  fhuc:
    vlan: 104
    ips: ["10.10.104.10/24"]
    gateway: "10.10.104.1"
  l2biphi:
    vlan: 105
    ips: ["10.10.105.10/24"]
    gateway: "10.10.105.1"
  l2biprt:
    vlan: 106
    ips: ["10.10.106.10/24"]
    gateway: "10.10.106.1"
  l1bipl1:
    vlan: 107
    ips: ["10.10.107.10/24"]
    gateway: "10.10.107.1"
  l1biprt:
    vlan: 108
    ips: ["10.10.108.10/24"]
    gateway: "10.10.108.1"
  oam:
    vlan: 109
    ips: ["10.10.109.10/24", "10.10.109.11/24"]
    gateway: "10.10.109.1"
  tracing:
    vlan: 110
    ips: ["10.10.110.10/24"]
    gateway: "10.10.110.1"
  twamp:
    vlan: 111
    ips: ["10.10.111.10/24"]
    gateway: "10.10.111.1"

files_path: "{{ role_path }}/files"
templates_path: "{{ role_path }}/templates"

ns:
  - "namespace.yaml"
  - "test-ns.yaml"

configmaps: "configmap.yaml"
secrets:
  - "secret.yaml"
  - "secrets/s1-1.yaml"
  - "secrets/s1-2.yaml"
  - "secrets/s10-1.yaml"
  - "secrets/s10-2.yaml"
  - "secrets/s100-2.yaml"
  - "secrets/s101-2.yaml"
  - "secrets/s102-2.yaml"
  - "secrets/s103-2.yaml"
  - "secrets/s104-2.yaml"
  - "secrets/s105-2.yaml"
  - "secrets/s106-2.yaml"
  - "secrets/s107-2.yaml"
  - "secrets/s108-2.yaml"
  - "secrets/s109-2.yaml"
  - "secrets/s11-1.yaml"
  - "secrets/s11-2.yaml"
  - "secrets/s110-2.yaml"
  - "secrets/s111-2.yaml"
  - "secrets/s112-2.yaml"
  - "secrets/s113-2.yaml"
  - "secrets/s114-2.yaml"
  - "secrets/s115-2.yaml"
  - "secrets/s116-2.yaml"
  - "secrets/s117-2.yaml"
  - "secrets/s118-2.yaml"
  - "secrets/s119-2.yaml"
  - "secrets/s12-1.yaml"
  - "secrets/s12-2.yaml"
  - "secrets/s120-2.yaml"
  - "secrets/s121-2.yaml"
  - "secrets/s122-2.yaml"
  - "secrets/s123-2.yaml"
  - "secrets/s124-2.yaml"
  - "secrets/s125-2.yaml"
  - "secrets/s126-2.yaml"
  - "secrets/s127-2.yaml"
  - "secrets/s128-2.yaml"
  - "secrets/s129-2.yaml"
  - "secrets/s13-1.yaml"
  - "secrets/s13-2.yaml"
  - "secrets/s130-2.yaml"
  - "secrets/s131-2.yaml"
  - "secrets/s132-2.yaml"
  - "secrets/s133-2.yaml"
  - "secrets/s134-2.yaml"
  - "secrets/s135-2.yaml"
  - "secrets/s136-2.yaml"
  - "secrets/s137-2.yaml"
  - "secrets/s138-2.yaml"
  - "secrets/s139-2.yaml"
  - "secrets/s14-1.yaml"
  - "secrets/s14-2.yaml"
  - "secrets/s140-2.yaml"
  - "secrets/s141-2.yaml"
  - "secrets/s142-2.yaml"
  - "secrets/s143-2.yaml"
  - "secrets/s144-2.yaml"
  - "secrets/s145-2.yaml"
  - "secrets/s146-2.yaml"
  - "secrets/s147-2.yaml"
  - "secrets/s148-2.yaml"
  - "secrets/s149-2.yaml"
  - "secrets/s15-1.yaml"
  - "secrets/s15-2.yaml"
  - "secrets/s150-2.yaml"
  - "secrets/s151-2.yaml"
  - "secrets/s152-2.yaml"
  - "secrets/s153-2.yaml"
  - "secrets/s154-2.yaml"
  - "secrets/s155-2.yaml"
  - "secrets/s156-2.yaml"
  - "secrets/s157-2.yaml"
  - "secrets/s158-2.yaml"
  - "secrets/s159-2.yaml"
  - "secrets/s16-1.yaml"
  - "secrets/s16-2.yaml"
  - "secrets/s160-2.yaml"
  - "secrets/s161-2.yaml"
  - "secrets/s162-2.yaml"
  - "secrets/s163-2.yaml"
  - "secrets/s164-2.yaml"
  - "secrets/s165-2.yaml"
  - "secrets/s166-2.yaml"
  - "secrets/s167-2.yaml"
  - "secrets/s168-2.yaml"
  - "secrets/s169-2.yaml"
  - "secrets/s17-1.yaml"
  - "secrets/s17-2.yaml"
  - "secrets/s170-2.yaml"
  - "secrets/s171-2.yaml"
  - "secrets/s172-2.yaml"
  - "secrets/s173-2.yaml"
  - "secrets/s174-2.yaml"
  - "secrets/s175-2.yaml"
  - "secrets/s176-2.yaml"
  - "secrets/s177-2.yaml"
  - "secrets/s178-2.yaml"
  - "secrets/s179-2.yaml"
  - "secrets/s18-1.yaml"
  - "secrets/s18-2.yaml"
  - "secrets/s180-2.yaml"
  - "secrets/s181-2.yaml"
  - "secrets/s182-2.yaml"
  - "secrets/s183-2.yaml"
  - "secrets/s184-2.yaml"
  - "secrets/s185-2.yaml"
  - "secrets/s186-2.yaml"
  - "secrets/s187-2.yaml"
  - "secrets/s188-2.yaml"
  - "secrets/s189-2.yaml"
  - "secrets/s19-1.yaml"
  - "secrets/s19-2.yaml"
  - "secrets/s190-2.yaml"
  - "secrets/s191-2.yaml"
  - "secrets/s192-2.yaml"
  - "secrets/s193-2.yaml"
  - "secrets/s194-2.yaml"
  - "secrets/s195-2.yaml"
  - "secrets/s196-2.yaml"
  - "secrets/s197-2.yaml"
  - "secrets/s198-2.yaml"
  - "secrets/s199-2.yaml"
  - "secrets/s2-1.yaml"
  - "secrets/s2-2.yaml"
  - "secrets/s20-1.yaml"
  - "secrets/s20-2.yaml"
  - "secrets/s200-2.yaml"
  - "secrets/s201-2.yaml"
  - "secrets/s202-2.yaml"
  - "secrets/s203-2.yaml"
  - "secrets/s204-2.yaml"
  - "secrets/s205-2.yaml"
  - "secrets/s206-2.yaml"
  - "secrets/s207-2.yaml"
  - "secrets/s208-2.yaml"
  - "secrets/s209-2.yaml"
  - "secrets/s21-1.yaml"
  - "secrets/s21-2.yaml"
  - "secrets/s210-2.yaml"
  - "secrets/s211-2.yaml"
  - "secrets/s212-2.yaml"
  - "secrets/s213-2.yaml"
  - "secrets/s214-2.yaml"
  - "secrets/s215-2.yaml"
  - "secrets/s216-2.yaml"
  - "secrets/s217-2.yaml"
  - "secrets/s218-2.yaml"
  - "secrets/s219-2.yaml"
  - "secrets/s22-1.yaml"
  - "secrets/s22-2.yaml"
  - "secrets/s220-2.yaml"
  - "secrets/s221-2.yaml"
  - "secrets/s222-2.yaml"
  - "secrets/s223-2.yaml"
  - "secrets/s224-2.yaml"
  - "secrets/s225-2.yaml"
  - "secrets/s226-2.yaml"
  - "secrets/s227-2.yaml"
  - "secrets/s228-2.yaml"
  - "secrets/s229-2.yaml"
  - "secrets/s23-1.yaml"
  - "secrets/s23-2.yaml"
  - "secrets/s230-2.yaml"
  - "secrets/s231-2.yaml"
  - "secrets/s232-2.yaml"
  - "secrets/s233-2.yaml"
  - "secrets/s234-2.yaml"
  - "secrets/s235-2.yaml"
  - "secrets/s236-2.yaml"
  - "secrets/s237-2.yaml"
  - "secrets/s238-2.yaml"
  - "secrets/s239-2.yaml"
  - "secrets/s24-1.yaml"
  - "secrets/s24-2.yaml"
  - "secrets/s240-2.yaml"
  - "secrets/s241-2.yaml"
  - "secrets/s242-2.yaml"
  - "secrets/s243-2.yaml"
  - "secrets/s244-2.yaml"
  - "secrets/s245-2.yaml"
  - "secrets/s246-2.yaml"
  - "secrets/s247-2.yaml"
  - "secrets/s248-2.yaml"
  - "secrets/s249-2.yaml"
  - "secrets/s25-1.yaml"
  - "secrets/s25-2.yaml"
  - "secrets/s250-2.yaml"
  - "secrets/s251-2.yaml"
  - "secrets/s252-2.yaml"
  - "secrets/s253-2.yaml"
  - "secrets/s254-2.yaml"
  - "secrets/s255-2.yaml"
  - "secrets/s256-2.yaml"
  - "secrets/s257-2.yaml"
  - "secrets/s258-2.yaml"
  - "secrets/s259-2.yaml"
  - "secrets/s26-1.yaml"
  - "secrets/s26-2.yaml"
  - "secrets/s260-2.yaml"
  - "secrets/s261-2.yaml"
  - "secrets/s262-2.yaml"
  - "secrets/s263-2.yaml"
  - "secrets/s264-2.yaml"
  - "secrets/s265-2.yaml"
  - "secrets/s266-2.yaml"
  - "secrets/s267-2.yaml"
  - "secrets/s268-2.yaml"
  - "secrets/s269-2.yaml"
  - "secrets/s27-1.yaml"
  - "secrets/s27-2.yaml"
  - "secrets/s270-2.yaml"
  - "secrets/s271-2.yaml"
  - "secrets/s272-2.yaml"
  - "secrets/s273-2.yaml"
  - "secrets/s274-2.yaml"
  - "secrets/s275-2.yaml"
  - "secrets/s276-2.yaml"
  - "secrets/s277-2.yaml"
  - "secrets/s278-2.yaml"
  - "secrets/s279-2.yaml"
  - "secrets/s28-1.yaml"
  - "secrets/s28-2.yaml"
  - "secrets/s280-2.yaml"
  - "secrets/s281-2.yaml"
  - "secrets/s282-2.yaml"
  - "secrets/s283-2.yaml"
  - "secrets/s284-2.yaml"
  - "secrets/s285-2.yaml"
  - "secrets/s286-2.yaml"
  - "secrets/s287-2.yaml"
  - "secrets/s288-2.yaml"
  - "secrets/s289-2.yaml"
  - "secrets/s29-1.yaml"
  - "secrets/s29-2.yaml"
  - "secrets/s290-2.yaml"
  - "secrets/s291-2.yaml"
  - "secrets/s292-2.yaml"
  - "secrets/s293-2.yaml"
  - "secrets/s294-2.yaml"
  - "secrets/s295-2.yaml"
  - "secrets/s296-2.yaml"
  - "secrets/s297-2.yaml"
  - "secrets/s298-2.yaml"
  - "secrets/s299-2.yaml"
  - "secrets/s3-1.yaml"
  - "secrets/s3-2.yaml"
  - "secrets/s30-1.yaml"
  - "secrets/s30-2.yaml"
  - "secrets/s300-2.yaml"
  - "secrets/s301-2.yaml"
  - "secrets/s302-2.yaml"
  - "secrets/s303-2.yaml"
  - "secrets/s304-2.yaml"
  - "secrets/s305-2.yaml"
  - "secrets/s306-2.yaml"
  - "secrets/s307-2.yaml"
  - "secrets/s308-2.yaml"
  - "secrets/s309-2.yaml"
  - "secrets/s31-1.yaml"
  - "secrets/s31-2.yaml"
  - "secrets/s310-2.yaml"
  - "secrets/s311-2.yaml"
  - "secrets/s312-2.yaml"
  - "secrets/s313-2.yaml"
  - "secrets/s314-2.yaml"
  - "secrets/s315-2.yaml"
  - "secrets/s316-2.yaml"
  - "secrets/s317-2.yaml"
  - "secrets/s318-2.yaml"
  - "secrets/s319-2.yaml"
  - "secrets/s32-1.yaml"
  - "secrets/s32-2.yaml"
  - "secrets/s320-2.yaml"
  - "secrets/s321-2.yaml"
  - "secrets/s322-2.yaml"
  - "secrets/s323-2.yaml"
  - "secrets/s324-2.yaml"
  - "secrets/s325-2.yaml"
  - "secrets/s326-2.yaml"
  - "secrets/s327-2.yaml"
  - "secrets/s328-2.yaml"
  - "secrets/s329-2.yaml"
  - "secrets/s33-1.yaml"
  - "secrets/s33-2.yaml"
  - "secrets/s330-2.yaml"
  - "secrets/s331-2.yaml"
  - "secrets/s332-2.yaml"
  - "secrets/s333-2.yaml"
  - "secrets/s334-2.yaml"
  - "secrets/s335-2.yaml"
  - "secrets/s336-2.yaml"
  - "secrets/s337-2.yaml"
  - "secrets/s338-2.yaml"
  - "secrets/s339-2.yaml"
  - "secrets/s34-1.yaml"
  - "secrets/s34-2.yaml"
  - "secrets/s340-2.yaml"
  - "secrets/s341-2.yaml"
  - "secrets/s342-2.yaml"
  - "secrets/s35-1.yaml"
  - "secrets/s35-2.yaml"
  - "secrets/s36-1.yaml"
  - "secrets/s36-2.yaml"
  - "secrets/s37-1.yaml"
  - "secrets/s37-2.yaml"
  - "secrets/s38-1.yaml"
  - "secrets/s38-2.yaml"
  - "secrets/s39-1.yaml"
  - "secrets/s39-2.yaml"
  - "secrets/s4-1.yaml"
  - "secrets/s4-2.yaml"
  - "secrets/s40-2.yaml"
  - "secrets/s41-2.yaml"
  - "secrets/s42-2.yaml"
  - "secrets/s43-2.yaml"
  - "secrets/s44-2.yaml"
  - "secrets/s45-2.yaml"
  - "secrets/s46-2.yaml"
  - "secrets/s47-2.yaml"
  - "secrets/s48-2.yaml"
  - "secrets/s49-2.yaml"
  - "secrets/s5-1.yaml"
  - "secrets/s5-2.yaml"
  - "secrets/s50-2.yaml"
  - "secrets/s51-2.yaml"
  - "secrets/s52-2.yaml"
  - "secrets/s53-2.yaml"
  - "secrets/s54-2.yaml"
  - "secrets/s55-2.yaml"
  - "secrets/s56-2.yaml"
  - "secrets/s57-2.yaml"
  - "secrets/s58-2.yaml"
  - "secrets/s59-2.yaml"
  - "secrets/s6-1.yaml"
  - "secrets/s6-2.yaml"
  - "secrets/s60-2.yaml"
  - "secrets/s61-2.yaml"
  - "secrets/s62-2.yaml"
  - "secrets/s63-2.yaml"
  - "secrets/s64-2.yaml"
  - "secrets/s65-2.yaml"
  - "secrets/s66-2.yaml"
  - "secrets/s67-2.yaml"
  - "secrets/s68-2.yaml"
  - "secrets/s69-2.yaml"
  - "secrets/s7-1.yaml"
  - "secrets/s7-2.yaml"
  - "secrets/s70-2.yaml"
  - "secrets/s71-2.yaml"
  - "secrets/s72-2.yaml"
  - "secrets/s73-2.yaml"
  - "secrets/s74-2.yaml"
  - "secrets/s75-2.yaml"
  - "secrets/s76-2.yaml"
  - "secrets/s77-2.yaml"
  - "secrets/s78-2.yaml"
  - "secrets/s79-2.yaml"
  - "secrets/s8-1.yaml"
  - "secrets/s8-2.yaml"
  - "secrets/s80-2.yaml"
  - "secrets/s81-2.yaml"
  - "secrets/s82-2.yaml"
  - "secrets/s83-2.yaml"
  - "secrets/s84-2.yaml"
  - "secrets/s85-2.yaml"
  - "secrets/s86-2.yaml"
  - "secrets/s87-2.yaml"
  - "secrets/s88-2.yaml"
  - "secrets/s89-2.yaml"
  - "secrets/s9-1.yaml"
  - "secrets/s9-2.yaml"
  - "secrets/s90-2.yaml"
  - "secrets/s91-2.yaml"
  - "secrets/s92-2.yaml"
  - "secrets/s93-2.yaml"
  - "secrets/s94-2.yaml"
  - "secrets/s95-2.yaml"
  - "secrets/s96-2.yaml"
  - "secrets/s97-2.yaml"
  - "secrets/s98-2.yaml"
  - "secrets/s99-2.yaml"
pvs:
  - "pv.yaml"
pvcs:
  - "pvc.yaml"
deployments:
  - "deployment.yaml"
  - "templates/test1-deployment.yaml"
  - "templates/test10-1-deployment.yaml"
  - "templates/test10-statefulset.yaml"
  - "templates/test11-statefulset.yaml"
  - "templates/test12-statefulset.yaml"
  - "templates/test13-statefulset.yaml"
  - "templates/test14-statefulset.yaml"
  - "templates/test15-statefulset.yaml"
  - "templates/test16-deployment.yaml"
  - "templates/test17-statefulset.yaml"
  - "templates/test18-deployment.yaml"
  - "templates/test19-deployment.yaml"
  - "templates/test19-statefulset.yaml"
  - "templates/test2-deployment.yaml"
  - "templates/test21-deployment.yaml"
  - "templates/test22-deployment.yaml"
  - "templates/test23-deployment.yaml"
  - "templates/test24-deployment.yaml"
  - "templates/test25-deployment.yaml"
  - "templates/test26-deployment.yaml"
  - "templates/test27-deployment.yaml"
  - "templates/test28-deployment.yaml"
  - "templates/test29-deployment.yaml"
  - "templates/test30-deployment.yaml"
  - "templates/test32-deployment.yaml"
  - "templates/test33-deployment.yaml"
  - "templates/test34-deployment.yaml"
  - "templates/test35-deployment.yaml"
  - "templates/test36-deployment.yaml"
  - "templates/test37-deployment.yaml"
  - "templates/test38-deployment.yaml"
  - "templates/test39-deployment.yaml"
  - "templates/test4-deployment.yaml"
  - "templates/test40-deployment.yaml"
  - "templates/test41-deployment.yaml"
  - "templates/test42-statefulset.yaml"
  - "templates/test43-deployment.yaml"
  - "templates/test44-deployment.yaml"
  - "templates/test45-statefulset.yaml"
  - "templates/test46-statefulset.yaml"
  - "templates/test47-deployment.yaml"
  - "templates/test48-deployment.yaml"
  - "templates/test49-deployment.yaml"
  - "templates/test5-deployment.yaml"
  - "templates/test50-deployment.yaml"
  - "templates/test6-statefulset.yaml"
  - "templates/test7-statefulset.yaml"
  - "templates/test8-statefulset.yaml"
  - "templates/test9-statefulset.yaml"
