- name: Install eDU
  hosts: cluster
  tasks:
    - name: Print KubeConfig
      debug:
        msg: "Value of kubeconfig {{ kubeconfig }}"
    - include_role:
        name: setup_edu
      vars:
        kubeconfig_path: "{{ kubeconfig }}"
