apiVersion: apps/v1
kind: Deployment
metadata:
  name: test27-deployment
  namespace: test
  labels:
    app: test27 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: test27 
  template:
    metadata:
      labels:
        app: test27
    spec: 
      containers: 
      - env:
        - name: SERVICE_NAME
          value: t27 
        - name: CONTAINER_NAME
          value: t27 
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: {{ registry_address }}:5000/test_images/spam_150_1_8001:latest 
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
           path: /
           port: 8001
          initialDelaySeconds: 5 
          periodSeconds: 30 
          successThreshold: 1
          timeoutSeconds: 20 
        name: t27 
        ports:
        - containerPort: 8001
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8001 
          initialDelaySeconds: 5 
          periodSeconds: 30 
          successThreshold: 1
          timeoutSeconds: 20 
        resources:
          limits:
            cpu: 100m 
            memory: 128Mi 
            ephemeral-storage: 3584Mi
          requests:
            cpu: 100m
            memory: 128Mi 
            ephemeral-storage: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
            - KILL
            - MKNOD
            - SETGID
            - SETUID
          privileged: false
          readOnlyRootFilesystem: false 
          runAsNonRoot: true
        volumeMounts: 
        - mountPath: /etc/certs/secrets/server
          name: tcp-server-cert
        - mountPath: /etc/certs/internalca/
          name: pm-event-exporter-ca
        - mountPath: /etc/certs/secrets/sip-tls/ca
          name: sip-tls-root-ca
      volumes:
      - name: tcp-server-cert
        secret:
          defaultMode: 420
          secretName: s106-2 
      - name: pm-event-exporter-ca
        secret:
          defaultMode: 420
          secretName: s105-2 
      - name: sip-tls-root-ca
        secret:
          defaultMode: 420
          secretName: s186-2 
