apiVersion: apps/v1
kind: Deployment
metadata:
  name: test24-deployment
  namespace: test
  labels:
    app: test24 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: test24 
  template:
    metadata:
      labels:
        app: test24
    spec: 
      containers: 
      - env:
        - name: SERVICE_NAME
          value: t24 
        - name: CONTAINER_NAME
          value: t24 
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: {{ registry_address }}:5000/test_images/spam_150_1_8001:latest 
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
           path: /
           port: 8001
          initialDelaySeconds: 3 
          periodSeconds: 3 
          successThreshold: 1
          timeoutSeconds: 15
        name: t24 
        ports:
        - containerPort: 8001
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8001 
          initialDelaySeconds: 3 
          periodSeconds: 3 
          successThreshold: 1
          timeoutSeconds: 15
        resources:
          limits:
            cpu: 500m 
            memory: 250M
            ephemeral-storage: 10Gi
          requests:
            cpu: 250m
            memory: 100M 
            ephemeral-storage: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - KILL
            - MKNOD
            - SETGID
            - SETUID
            - all
          privileged: false
          readOnlyRootFilesystem: false 
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /sdata
          name: s-data
        - mountPath: /upload
          name: upload
        - mountPath: /etc/opt/
          name: sftp-credentials-volume
          readOnly: true
        - mountPath: /run/secrets/tls-int-ca-certs
          name: trusted-ca
        - mountPath: /run/secrets/lt-client-cert
          name: lt-client-cert
          readOnly: true
        - mountPath: /run/secrets/cmm-server-cert
          name: cmm-server-cert
          readOnly: true
        - mountPath: /run/secrets/pms-server-cert
          name: pms-scrape-server-cert
          readOnly: true
        - mountPath: /run/secrets/pms-rw-server-cert
          name: pms-rw-server-cert
          readOnly: true
        - mountPath: /run/secrets/pm-rw-ca
          name: pm-rw-ca
          readOnly: true
        - mountPath: /run/secrets/pm-ca
          name: pm-ca
          readOnly: true
        - mountPath: /run/secrets/se-client-cert
          name: se-client-cert
          readOnly: true
        - mountPath: /run/secrets/probes-server-cert
          name: probes-server-cert
          readOnly: true
        - mountPath: /run/secrets/cmm-cert
          name: cmm-cert
          readOnly: true
        - mountPath: /run/secrets/cmm-ca
          name: cmm-ca
          readOnly: true
        - mountPath: /run/secrets/ddb-encyption-key
          name: ddb-encyption-key
          readOnly: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: datadir-data-7
      -  emptyDir: {}
         name: s-data
      - emptyDir: {}
        name: upload
      - name: sftp-credentials-volume
        secret:
          defaultMode: 420
          secretName: s120-2 
      - name: trusted-ca
        secret:
          defaultMode: 420
          secretName: s186-2 
      - name: probes-server-cert
        secret:
          defaultMode: 420
          secretName: s96-2 
      - name: lt-client-cert
        secret:
          defaultMode: 420
          secretName: s93-2
      - name: cmm-server-cert
        secret:
          defaultMode: 420
          secretName: s91-2 
      - name: pms-scrape-server-cert
        secret:
          defaultMode: 420
          secretName: s95-2
      - name: pms-rw-server-cert
        secret:
          defaultMode: 420
          secretName: s94-2 
      - name: pm-rw-ca
        secret:
          defaultMode: 420
          secretName: s21-1 
      - name: pm-ca
        secret:
          defaultMode: 420
          optional: true
          secretName: s20-1 
      - name: se-client-cert
        secret:
          defaultMode: 420
          secretName: s97-2 
      - name: cmm-cert
        secret:
          defaultMode: 420
          secretName: s90-2 
      - name: cmm-ca
        secret:
          defaultMode: 420
          secretName: s2-1 
      - name: ddb-encyption-key
        secret:
          defaultMode: 420
          optional: true
          secretName: s19-1
         
