apiVersion: apps/v1
kind: Deployment
metadata:
  name: test30-deployment
  namespace: test
  labels:
    app: test30 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: test30 
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{"name": "ztp-sriov-nw-du-fh", "namespace": "test" }, {"name": "ztp-sriov-net-f1", "namespace": "test" }]'
      labels:
        app: test30
    spec: 
      containers: 
      - env:
        - name: TZ
          value: UTC
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: {{ registry_address }}:5000/ubi8/ubi
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 10;done"]
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - ls 
          failureThreshold: 3
          initialDelaySeconds: 30 
          periodSeconds: 10 
          successThreshold: 1
          timeoutSeconds: 1
        name: t30-1
        resources:
          limits:
            cpu: "2" 
            memory: 512Mi
            openshift.io/du_fh: "1" 
            openshift.io/pci_sriov_net_f1: "1"
          requests:
            cpu: "1" 
            memory: 512Mi
            openshift.io/du_fh: 1 
            openshift.io/pci_sriov_net_f1: "1"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - MKNOD  
            - all
          privileged: false
          readOnlyRootFilesystem: true 
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /tmp/cores
          name: shared-cores
        - mountPath: /var/log
          name: var-log
        - mountPath: /var/run/lttng
          name: lttng-unix-socket
        - mountPath: /tmp/lttng
          name: lttng-runtime
        - mountPath: /mnt/lttng
          name: shared-pid-file
        - mountPath: /etc/certs/ca
          name: root-ca
          readOnly: true
        - mountPath: /etc/certs/cm
          name: cm-cert
          readOnly: true
        - mountPath: /etc/certs/fm
          name: fm-cert
          readOnly: true
        - mountPath: /logs/
          name: log-shipper-storage-path
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: {{ registry_address }}:5000/test_images/spam_150_1_8001:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 8001
          failureThreshold: 6 
          initialDelaySeconds: 5 
          periodSeconds: 10 
          successThreshold: 1
          timeoutSeconds: 7 
        name: t30-2
        resources:
          limits:
            cpu: "2" 
            memory: 512Mi 
          requests:
            cpu: 100m 
            memory: 512Mi 
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
             - ALL
             - MKNOD
          privileged: false
          readOnlyRootFilesystem: true 
          runAsNonRoot: true
        volumeMounts:
         - mountPath: /tmp/cores
           name: shared-cores
         - mountPath: /data
           name: data
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: {{ registry_address }}:5000/ubi8/ubi
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 10;done"]
        imagePullPolicy: IfNotPresent
        readinessProbe:
          exec:
            command:
            - ls
          failureThreshold: 5 
          initialDelaySeconds: 5  
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 5 
        name: t30-3
        resources:
          limits:
            cpu: "2"
            memory: 384Mi
          requests:
            cpu: 100m 
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
             - ALL 
             - MKNOD
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /var/run/lttng
          name: lttng-unix-socket
        - mountPath: /tmp/lttng
          name: lttng-runtime
        - mountPath: /dev/shmem
          name: shmem
        - mountPath: /mnt/lttng
          name: shared-pid-file
        - mountPath: /data
          name: data  
        - mountPath: /etc/lttng-cert
          name: lttng-cert
        - mountPath: /run/secrets/sip-tls-root-ca
          name: lttng-rootcerts
      - env:
        - name: MESSAGE_LEN
          value: "240"
        - name: LOG_PERIOD_SEC
          value: "1/5"
        - name: POD_NAME
          valueFrom:
            fieldRef:
               fieldPath: metadata.name
        image: {{ registry_address }}:5000/test_images/logging:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - ls
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 15
        name: sidecar-1 
        resources:
          limits:
            cpu: 125m 
            memory: 50Mi
          requests:
            cpu: 35m 
            memory: 18Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
             - MKNOD
             - all
          privileged: false
          readOnlyRootFilesystem: false 
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /logs/
          name: log-shipper-storage-path
        - mountPath: /run/secrets/ca-certificates/
          name: server-ca-certificate
          readOnly: true
        - mountPath: /run/secrets/certificates/
          name: lt-client-cert
          readOnly: true
      initContainers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: {{ registry_address }}:5000/ubi8/ubi
        imagePullPolicy: IfNotPresent
        name: t30-init
#fix me 
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
             - MKNOD
             - all 
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
      - emptyDir: {}
        name: var-log
      - emptyDir: {}
        name: shared-cores
      - emptyDir: {}
        name: lttng-unix-socket
      - emptyDir: {}
        name: lttng-runtime
      - emptyDir: {}
        name: shared-pid-file
      - emptyDir: {}
        name: shmem
      - name: data
        persistentVolumeClaim:
          claimName: datadir-data-7
      - name: root-ca
        projected:
          defaultMode: 420
          sources:
          - secret:
              name: s186-2 
      - name: cm-cert
        secret:
          defaultMode: 420
          secretName: s114-2
      - name: fm-cert
        secret:
          defaultMode: 420
          secretName: s115-2 
      - name: lttng-cert
        secret:
          defaultMode: 420
          secretName: s117-2 
      - name: lttng-rootcerts
        secret:
          defaultMode: 420
          secretName: s186-2 
      - emptyDir:
          sizeLimit: 50Mi
        name: log-shipper-storage-path
      - name: server-ca-certificate
        secret:
          defaultMode: 420
          optional: true
          secretName: s186-2 
      - name: lt-client-cert
        secret:
          defaultMode: 420
          optional: true
          secretName: s116-2 
