# Template file for emulated DU

deployments:
  - volumes:
      # - name: volume-1
      #   persistentVolumeClaim: 1
      - name: volume-2
        secret: 1
      - name: volume-3
        configMap: 1
    pods:
      - name: pod_cpu_stress
        repeat: 2
        env:
          - name: stress_cpu
            value: '4'
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1000m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"

  - volumes:
    pods:
      - name: pod_vm_stress
        repeat: 2
        env:
          - name: stress_vm
            value: '4'
          - name: stress_vm-bytes
            value: '1024M'
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1000m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
      # - name: pod_nw_stress
      #   repeat: 1
      #   env:
      #     - name: stress_icmp-flood
      #       value: '4'  
      #     - name: stress_ping-sock
      #       value: '4'