# Template file for emulated DU

deployments:
  - volumes:
      # - name: volume-1
      #   persistentVolumeClaim: 1
      - name: volume-2
        secret: 1
      - name: volume-3
        configMap: 1
    pods:
      - name: pod_stress
        repeat: 3
        env:
          - name: stress_cpu
            value: '4'
          - name: stress_vm
            value: '4'
          - name: stress_vm-bytes
            value: '256M'
          # - name: stress_icmp-flood
          #   value: '4'  
          # - name: stress_ping-sock
          #   value: '4'