# Template file for emulated DU

deployments:
  - volumes:
      # - name: volume-1
      #   configMap: 1
      # - name: volume-2
      #   secret: 1
      # - name: volume-3
      #   persistentVolumeClaim: 1

    pods:
      - name: pod_vm_stress
        repeat: 1
        env:
          - name: stress_vm
            value: "1"
          - name: stress_vm-bytes
            value: "16M"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        resources:
          requests:
            memory: "1024Mi"
            # cpu: "1000m"
          limits:
            memory: "1024Mi"
            # cpu: "1000m"

  # - volumes:
  #   pods:
  #     - name: pod_vm_stress
  #       repeat: 2
  #       env:
  #         - name: stress_vm
  #           value: "4"
  #         - name: stress_vm-bytes
  #           value: "128M"
  #       livenessProbe:
  #         httpGet:
  #           path: /healthz
  #           port: 8080
  #       resources:
  #         requests:
  #           memory: "1024Mi"
  #           cpu: "1000m"
  #         limits:
  #           memory: "1024Mi"
  #           cpu: "1000m"
  # - name: pod_nw_stress
  #   repeat: 1
  #   env:
  #     - name: stress_icmp-flood
  #       value: '4'
  #     - name: stress_ping-sock
  #       value: '4'
