volumes:
  # - name: volume-1
  #   persistentVolumeClaim: 1
  - name: volume-2
    secret: 1
  - name: volume-3
    configMap: 1

containers:
  - name: container1
    env:
      - name: stress_cpu
        value: '4'
      - name: stress_vm
        value: '4'
      - name: stress_vm-bytes
        value: '256M'
    # volumeMounts:
    #   - name: volume-1



