apiVersion: v1
kind: Namespace
metadata:
  name: edu-namespace-0
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
